name:                AoC19
version:             0.1.0.0
github:              "thopper21/AoC19"
license:             BSD3
author:              "Taylor Hopper"
maintainer:          "taylorhopper@outlook.com"
copyright:           "2019 Taylor Hopper"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thopper21/AoC19#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- split
- parsec

library:
  source-dirs: src

executables:
  AoC19-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AoC19
